name: wechat_assets_picker
version: 8.7.1
description: |
  An image picker (also with videos and audio)
  for Flutter projects based on WeChat's UI,
  with full support for customization.
topics:
  - picker
  - image
  - audio
  - video
  - wechat

repository: https://github.com/fluttercandies/flutter_wechat_assets_picker
issue_tracker: https://github.com/fluttercandies/flutter_wechat_assets_picker/issues

environment:
  sdk: ^3.1.0
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^8.1.0
  photo_manager: ^2.7.0
  provider: ^6.0.5
  video_player: ^2.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: any
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Screenshot 1'
    path: screenshots/README_1.webp
  - description: 'Screenshot 2'
    path: screenshots/README_2.webp
  - description: 'Screenshot 3'
    path: screenshots/README_3.webp
  - description: 'Screenshot 4'
    path: screenshots/README_4.webp
  - description: 'Screenshot 5'
    path: screenshots/README_5.webp
  - description: 'Screenshot 6'
    path: screenshots/README_6.webp
  - description: 'Screenshot 7'
    path: screenshots/README_7.webp
  - description: 'Screenshot 8'
    path: screenshots/README_8.webp
  - description: 'Screenshot 9'
    path: screenshots/README_9.webp

flutter:
  uses-material-design: true
  fonts:
    - family: NimbusBold
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Bold-Extended_32745.ttf
    - family: NimbusRegular
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Regular-Extended_32755.ttf
    - family: NimbusRegularItalic
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Regular-Italic_32756.ttf
    - family: NimbusLight
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Light_32752.ttf
    - family: Nimbus
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT_32758.ttf
    - family: NimbusBlackBold
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Black-Extended_32740.ttf
    - family: NimbusItalic
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Bold-Italic_32746.ttf
    - family: NimbusLightItalic
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Light-Italic_32751.ttf
    - family: NimbusSansBold
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Bold_32747.ttf
    - family: NimbusReg
      fonts:
        - asset: fonts/nimbus-sans-l.regular.otf
